# Elasticsearch Ingress
{{- if .Values.lsdmopagent.elastic.fleet.enabled -}}
{{- if or (eq .Values.lsdmopagent.clusterType "gke") (eq .Values.lsdmopagent.clusterType "rancher") -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: fleet-server-{{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"    
  name: fleet-server-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.lsdmopagent.elastic.fleet.ingress.url }}
      secretName: {{ .Values.lsdmopagent.elastic.fleet.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.lsdmopagent.elastic.fleet.ingress.url }}
    http:
      paths:
      - backend:
          service:
            name: fleet-server-lsdmop-agent-http
            port: 
              number: 8220
        path: /
        pathType: ImplementationSpecific
---
{{- end }}
{{- end }}