# Elastic Filebeat
{{- if .Values.lsdmopagent.elastic.filebeat.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}-elastic-beat-autodiscover
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-elastic-beat-autodiscover-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-elastic-beat-autodiscover
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-filebeat
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-filebeat
{{- with .Values.lsdmopagent.elastic.filebeat.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}-filebeat-k8s
  namespace: {{ .Release.Namespace }}
spec:
  type: filebeat
  version: {{ .Values.lsdmopagent.elastic.filebeat.version }}
  image: {{ .Values.lsdmopagent.elastic.filebeat.image }}
  config:
    filebeat.inputs:
      - close_inactive: 4h
        exclude_files:
          - ^*_lsdmopagent_*$
        multiline:
          match: after
          negate: false
          pattern: '^[[:space:]]+|^Caused by:'
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: /var/log/containers/
        type: container
    output.logstash:
      hosts:
        - lsdmopagent-logstash:5044
    path.data: /usr/share/lsdmopagent-filebeat-k8s/data

  daemonSet:
    podTemplate:
      metadata:
        labels:
          scrape: bt
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        serviceAccountName: {{ .Release.Name }}-filebeat
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          name: filebeat
          resources:
            requests:
              memory: 256Mi
              cpu: 10m
            limits:
              memory: 512Mi
              cpu: 200m
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        tolerations: 
          - key: "node-role.kubernetes.io/controlplane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/etcd"
            operator: "Exists"
            effect: "NoExecute"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
          - key: dedicated
            effect: "NoSchedule"
            operator: Exists
{{- end }}

