{{- if .Values.elastic.ad.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: lsdmop-es-ad-bind-user
  namespace: {{ .Release.namespace }}
type: Opaque
stringData:
  ObserveAD: {{ .Values.elastic.ad.bindpassword | quote }}
{{- end }}