apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search-{{ .Release.Name }}
  namespace: lsdmop
spec:
  config:
    # define the exposed URL at which users will reach Enterprise Search
    ent_search.external_url: https://entsearch.mop.sandbox.internal.lsdopen.io:443
    # define the exposed URL at which users will reach Kibana
    kibana.host: https://kibana.mop.sandbox.internal.lsdopen.io:443
    # configure app search document size limit
    app_search.engine.document_size.limit: 1024kb  
  version: "{{ .Values.lsdmop.elastic.version }}"
  count: 1
  elasticsearchRef:
    name: {{ .Release.Name }}
