# Elastic ConfigMaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-filebeat-custom-files
data:
  lsdmop-filebeat.template.infra.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.template.infra.json" | indent 4}}
  lsdmop-filebeat.template.lsdo.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.template.lsdo.json" | indent 4}}
  lsdmop-filebeat.template.apps.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.template.apps.json" | indent 4}}
  lsdmop-filebeat.ilm.policy.infra.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.ilm.policy.infra.json" | indent 4}}
  lsdmop-filebeat.ilm.policy.lsdo.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.ilm.policy.lsdo.json" | indent 4}}
  lsdmop-filebeat.ilm.policy.apps.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.ilm.policy.apps.json" | indent 4}}
  lsdmop-filebeat.template.8.2.2.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.template.8.2.2.json" | indent 4}}
  lsdmop-filebeat.component.template.infra.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.component.template.infra.json" | indent 4}}
  lsdmop-filebeat.component.template.lsdo.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.component.template.lsdo.json" | indent 4}}
  lsdmop-filebeat.component.template.apps.json: |-
{{ .Files.Get "elastic/lsdmop-filebeat.component.template.apps.json" | indent 4}}
  lsdmop-elastic-load-sample-dashboard.ndjson: |-
{{ .Files.Get "elastic/lsdmop-elastic-load-sample-dashboard.ndjson" | indent 4}}
---
