apiVersion: v1
kind: Secret
metadata:
  name: eck-license-temp
  namespace: {{ .Release.Namespace }}
  labels:
    license.k8s.elastic.co/scope: operator
type: Opaque
data:
  license: >-
    base64encodedlicense
