# Elasticsearch
{{- if .Values.lsdmop.elastic.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-elastic
{{- with .Values.lsdmop.elastic.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
---              
{{- end }}
