
# Fleet APM Ingress

{{ if .Values.elastic.fleetapm.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lsdmop-apm
  namespace: {{ .Release.namespace }}
  labels:
    app: apm-server-agent
{{- with .Values.elastic.fleetapm.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.elastic.fleetapm.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.elastic.fleetapm.ingress.url }}
      secretName: {{ .Values.elastic.fleetapm.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.elastic.fleetapm.ingress.url }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Namespace }}-apm-http
                port:
                  number: 8200

{{- end }}
