# Elasticsearch
{{- if .Values.lsdmop.elastic.enabled -}}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.lsdmop.elastic.autoscaling.enabled }}
  annotations:
    elasticsearch.alpha.elastic.co/autoscaling-spec: |-
      {
          "pollingPeriod": "20s",
          "policies": [{
            "name": "hot-data",
            "roles": ["master", "data_hot", "data", "transform", "remote_cluster_client", "ingest"],
            "resources": {
                "nodeCount": { "min": {{ .Values.lsdmop.elastic.cluster.hot.count }}, "max": {{ .Values.lsdmop.elastic.cluster.hot.maxcount }} }
            }
          },
          {
            "name": "warm-data",
            "roles": ["master", "data_warm", "data", "data_content", "transform", "remote_cluster_client", "ingest"],
            "resources": {
                "nodeCount": { "min": {{ .Values.lsdmop.elastic.cluster.warm.count }}, "max": {{ .Values.lsdmop.elastic.cluster.warm.maxcount }} }
            }
          },
          {
            "name": "ml",
            "roles": ["ml"],
            "resources": {
                "nodeCount": { "min": {{ .Values.lsdmop.elastic.cluster.ml.count }}, "max": {{ .Values.lsdmop.elastic.cluster.ml.maxcount }} }
            }
          }]
      }
{{- end}}    
spec:
  version: "{{ .Values.lsdmop.elastic.version }}"
  podDisruptionBudget:
    metadata: {}
    spec:
      maxUnavailable: 1
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: {{ .Release.Name }}
  http:
    service:
      metadata: {}
      spec:
        selector:
          common.k8s.elastic.co/type: elasticsearch
          elasticsearch.k8s.elastic.co/cluster-name: {{ .Release.Name }}
    tls:
      certificate: {}
  transport:
    service:
      metadata: { }
      spec:
        selector:
          common.k8s.elastic.co/type: elasticsearch
          elasticsearch.k8s.elastic.co/cluster-name: {{ .Release.Name }}
          elasticsearch.k8s.elastic.co/node-data: "true"
    tls:
      certificate: { }
      certificateAuthorities: { }
  nodeSets:
{{- range $name, $nodeSet := .Values.lsdmop.elastic.nodeSets }}
    - config:
        node.store.allow_mmap: false
        #path.repo: /usr/share/elasticsearch/snapshots
        {{- if not empty $nodeSet.roles }}
        node.roles:
          {{ $nodeSet.roles | toYaml | indent 10 | trim }}
        {{- end }}
        {{- range $key, $val := $nodeSet.node_attributes }}
        node.attr.{{ $key }}: {{ $val }}
        {{- end }}
        http.max_content_length: 100mb
        http.compression: true
        transport.compress: true
        xpack:
          security:
            authc:
              api_key:
                enabled: true #required for fleet
{{- if $.Values.lsdmop.elastic.ad.enabled }}
              realms:
                native:
                  native1:
                    order: 0
                {{- range $key, $val := $.Values.lsdmop.elastic.ad.realms }}
                {{ $key }}:
                  {{ $val | toYaml | indent 18 | trim  }}
                {{- end }}                        
{{- end }}          
      count: {{ $nodeSet.count }}
      name: {{ $name }}
      podTemplate:
        metadata:
          labels:
            scrape: es
        spec:
          serviceAccountName: {{ $.Release.Name }}-elastic
          serviceAccount: {{ $.Release.Name }}-elastic
          automountServiceAccountToken: true
          hostAliases:
            {{ $.Values.lsdmop.elastic.hostAliases | toYaml | indent 12 | trim  }}
          initContainers:
            - name: set-s3-bucket-web-token-dir
              command:
              - mkdir
              - -p
              - /usr/share/elasticsearch/config/repository-s3
            - name: remove-s3-bucket-web-token-symlink
              command:
              - rm
              - -rf
              - /usr/share/elasticsearch/config/repository-s3/aws-web-identity-token-file
            - name: set-s3-bucket-web-token-symlink
              command:
              - ln
              - -s
              - /var/run/secrets/eks.amazonaws.com/serviceaccount/token 
              - "/usr/share/elasticsearch/config/repository-s3/aws-web-identity-token-file"
          containers:
            - env:
                - name: ZONE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['topology.kubernetes.io/zone']
                {{ if $.Values.lsdmop.elastic.ad.enabled }}
                - name: AD_BIND_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: lsdmop-es-ad-bind-user
                      key: ObserveAD
                      optional: true
                {{- end }}
              name: elasticsearch
              resources: 
                {{ $nodeSet.resources | toYaml | indent 16 | trim }}
          tolerations: 
            {{ $nodeSet.tolerations | toYaml | indent 12 | trim }}
          {{- with $nodeSet.nodeSelector }}
          nodeSelector:
          {{ toYaml . | indent 12 }}
          {{- end }}
      volumeClaimTemplates:
        - metadata:
            creationTimestamp: null
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ $nodeSet.storageSize }}
            storageClassName: {{ $nodeSet.storageClassName }}
{{- end }}
---     
{{- end }}
