# Kibana CRD
{{- if .Values.lsdmop.elastic.kibana.enabled -}}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    scrape: kb
spec:
  version: "{{ .Values.lsdmop.elastic.version }}"
  count: {{ .Values.lsdmop.elastic.kibana.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}
    serviceName: {{ .Release.Name }}-elasticsearch-coordinating-nodes
{{- if .Values.lsdmop.elastic.enterprise_search.enabled }}
  enterpriseSearchRef:
    name: enterprise-search-{{ .Release.Name }}
{{- end }}
  config:
    elasticsearch.compression: true
{{- if .Values.lsdmop.elastic.enterprise_search.enabled }}
    enterpriseSearch.host: https://enterprise-search-{{ .Release.Name }}-ent-http:3002
{{- end }}
    monitoring.ui.ccs.enabled: false #prevents a bug 
    xpack.encryptedSavedObjects.encryptionKey: "37LxDnDT9dy*J2DcTE7UQJW6mw@sMmqj"

{{- if .Values.lsdmop.elastic.fleet.enabled }}
    xpack.fleet.agents.elasticsearch.hosts: ["https://lsdmop-es-http.lsdmop.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: 
      - https://fleet-server-lsdmop-agent-http.lsdmop.svc:8220
      - https://{{ .Values.lsdmop.elastic.fleet.fleetURL }}:443
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: kubernetes
        version: latest
      - name: apm
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_default_fleet_server: true
        namespace: {{ .Release.Namespace }}
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent-1
        namespace: {{ .Release.Namespace }}
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system    
          - name: kubernetes-1
            id: kubernetes-1
            package:
              name: kubernetes  
      - name: Elastic APM policy
        id: eck-apm-1
        namespace: {{ .Release.Namespace }}
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-2
            id: system-2
            package:
              name: system    
          - name: kubernetes-2
            id: kubernetes-2
            package:
              name: kubernetes  
          - name: apm-2
            id: apm-2
            package:
              name: apm
            inputs:
            - type: apm
              enabled: true
              vars:
              - name: host
                value: 0.0.0.0:8200
      # - name: Kubernetes Monitoring on ECK policy
      #   id: eck-agent-k8s
      #   namespace: {{ .Release.Namespace }}
      #   monitoring_enabled:
      #     - logs
      #     - metrics
      #   unenroll_timeout: 900
      #   is_default: true
      #   package_policies:
      #     - name: kubernetes-2
      #       id: kubernetes-2
      #       package:
      #         name: kubernetes  
{{- end }}            
  podTemplate:
    metadata:
      labels:
        scrape: kb      
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    common.k8s.elastic.co/type: kibana
                    kibana.k8s.elastic.co/name: lsdmop
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 4000m
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Exists
  http:
    tls:
      #selfSignedCertificate:
        #disabled: true
      selfSignedCertificate:
        #secretName: {{ .Values.lsdmop.elastic.kibana.ingress.tls.secretName }}
        subjectAltNames:
        #- ip: 160.46.176.15
        - dns: {{ .Values.lsdmop.elastic.kibana.ingress.url }}
        
---
{{- end }}
