{{- if .Values.lsdmop.elastic.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: elastic-post-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      #VOLUMES FOR CONFIG MAPS - always at end
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          name: elastic-filebeat-custom-files
        name: elastic-filebeat-custom-files     

      initContainers:
      #WAIT FOR ELASTIC TO START ACCEPTING API CALLS
      - args:
        - /bin/sh
        - -c
        - |
          set -x; while [ "$(curl -u elastic:$ELASTIC_PASSWORD -ks https://lsdmop-es-http:9200/_cluster/health?pretty | grep status | sed -r 's/^[^:]*:(.*),+$/\1/' | sed -r 's/[[:space:]\"]*//g')" != "green" ]; do
            sleep 5;
          done;
          sleep 60;
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: wait-for-elastic
      containers:

      #DEBUG SLEEP CONTAINER
      - args:
        - -c
        - "sleep 1"
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: sleep-debug-container
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files

      #ILM POLICIES
      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.ilm.policy.infra.json \"https://lsdmop-es-http:9200/_ilm/policy/filebeat-infra\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-ilm-policy-infra
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files

      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.ilm.policy.lsdo.json \"https://lsdmop-es-http:9200/_ilm/policy/filebeat-lsdo\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-ilm-policy-lsdo
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files

      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.ilm.policy.apps.json \"https://lsdmop-es-http:9200/_ilm/policy/filebeat-apps\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-ilm-policy-apps
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files





      #COMPONENT TEMPLATES    
      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.template.8.2.2.json \"https://lsdmop-es-http:9200/_component_template/filebeat-8.2.2\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-component-template
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files

      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.component.template.infra.json \"https://lsdmop-es-http:9200/_component_template/filebeat-infra\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-component-template-infra
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files

      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.component.template.lsdo.json \"https://lsdmop-es-http:9200/_component_template/filebeat-lsdo\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-component-template-lsdo
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files

      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.component.template.apps.json \"https://lsdmop-es-http:9200/_component_template/filebeat-apps\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-component-template-apps
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files 




      #COMPONENTISED INDEX TEMPLATES
      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.template.apps.json \"https://lsdmop-es-http:9200/_index_template/filebeat-apps\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-template-apps
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files 

      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.template.lsdo.json \"https://lsdmop-es-http:9200/_index_template/filebeat-lsdo\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-template-lsdo
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files 

      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.template.infra.json \"https://lsdmop-es-http:9200/_index_template/filebeat-infra\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-template-infra
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files 

      # BOOTSTRAP DATASTREAMS  PUT _data_stream/my-data-stream
      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT \"https://lsdmop-es-http:9200/_data_stream/filebeat-8.2.2-infra\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-bootstrap-infra
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files

      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT \"https://lsdmop-es-http:9200/_data_stream/filebeat-8.2.2-lsdo\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-bootstrap-lsdo
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
          
      - args:
        - -c
        - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT \"https://lsdmop-es-http:9200/_data_stream/filebeat-8.2.2-apps\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: filebeat-bootstrap-apps
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files


      # # BOOTSTRAP ILM INDICES -- DEPRECATED FOR DATASTREAMS
      # - args:
      #   - -c
      #   - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.bootstrap.infra.json \"https://lsdmop-es-http:9200/%3Cfilebeat-8.2.2-infra-%7Bnow%2Fd%7D-000001%3E\""
      #   command:
      #   - /bin/sh
      #   env:
      #     - name: ELASTIC_PASSWORD
      #       valueFrom:
      #         secretKeyRef:
      #           name: lsdmop-es-elastic-user
      #           key: elastic
      #   image: {{ .Values.lsdmop.curl.image }}
      #   name: filebeat-bootstrap-infra
      #   volumeMounts:
      #   - mountPath: /opt/elastic/
      #     name: elastic-filebeat-custom-files
      # - args:
      #   - -c
      #   - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.bootstrap.lsdo.json \"https://lsdmop-es-http:9200/%3Cfilebeat-8.2.2-lsdo-%7Bnow%2Fd%7D-000001%3E\""
      #   command:
      #   - /bin/sh
      #   env:
      #     - name: ELASTIC_PASSWORD
      #       valueFrom:
      #         secretKeyRef:
      #           name: lsdmop-es-elastic-user
      #           key: elastic
      #   image: {{ .Values.lsdmop.curl.image }}
      #   name: filebeat-bootstrap-lsdo
      #   volumeMounts:
      #   - mountPath: /opt/elastic/
      #     name: elastic-filebeat-custom-files
      # - args:
      #   - -c
      #   - "curl -skv -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdmop-filebeat.bootstrap.apps.json \"https://lsdmop-es-http:9200/%3Cfilebeat-8.2.2-apps-%7Bnow%2Fd%7D-000001%3E\""
      #   command:
      #   - /bin/sh
      #   env:
      #     - name: ELASTIC_PASSWORD
      #       valueFrom:
      #         secretKeyRef:
      #           name: lsdmop-es-elastic-user
      #           key: elastic
      #   image: {{ .Values.lsdmop.curl.image }}
      #   name: filebeat-bootstrap-apps
      #   volumeMounts:
      #   - mountPath: /opt/elastic/
      #     name: elastic-filebeat-custom-files



      #LOAD DASHBOARDS    
      - args:
        - -c
        - "curl -kv -u elastic:$ELASTIC_PASSWORD -H \"kbn-xsrf: true\" -X POST --form file=@/opt/elastic/lsdmop-elastic-load-sample-dashboard.ndjson https://lsdmop-kb-http:5601/api/saved_objects/_import?createNewCopies=false"
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: elastic-load-sample-dashboard
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files


{{- if .Values.lsdmop.elastic.s3snapshot.enabled }}

      #LOAD S3 Repo Config for Snapshots    
      - args:
        - -c
        - "curl -kv -u elastic:$ELASTIC_PASSWORD -H \"Content-Type: application/json\" -X PUT -d '{\"type\": \"s3\",\"settings\": {\"bucket\": \"{{ .Values.lsdmop.elastic.s3snapshot.bucket }}\"}}' https://lsdmop-es-http.lsdmop.svc:9200/_snapshot/s3_repository"
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: elastic-load-snapshot-repo
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files


      #LOAD S3 Daily Policy Config for Snapshots    
      - args:
        - -c
        - "curl -kv -u elastic:$ELASTIC_PASSWORD -H \"Content-Type: application/json\" -X PUT -d @/opt/elastic/lsdmop-elastic-load-snapshot-policy-daily.ndjson https://lsdmop-es-http.lsdmop.svc:9200/_slm/policy/cluster-state-daily"
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: elastic-load-snapshot-policy-daily
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files


      #LOAD S3 Hourly Policy Config for Snapshots    
      - args:
        - -c
        - "curl -kv -u elastic:$ELASTIC_PASSWORD -H \"Content-Type: application/json\" -d @/opt/elastic/lsdmop-elastic-load-snapshot-policy-hourly.ndjson https://lsdmop-es-http.lsdmop.svc:9200/_slm/policy/cluster-state-hourly"
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmop-es-elastic-user
                key: elastic
        image: {{ .Values.lsdmop.curl.image }}
        name: elastic-load-snapshot-policy-hourly
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files   
{{- end }}






---
{{- end }}
