{{- if .Values.elastic.kibana.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- with .Values.elastic.kibana.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}   
  labels:
    app: kibana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"    
  name: lsdmop-kb
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.elastic.kibana.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.elastic.kibana.ingress.url }}
      secretName: {{ .Values.elastic.kibana.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.elastic.kibana.ingress.url }}
    http:
      paths:
      - backend:
          service:
            name: lsdmop-kb-http
            port:
              number: 5601
        path: /
        pathType: ImplementationSpecific
---
{{- end }}
