{{- if .Values.lsdmop.elastic.ad.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: lsdmop-es-ad-bind-user
  namespace: lsdmop
type: Opaque
data:
  ObserveAD: {{ .Values.lsdmop.elastic.ad.bindpassword }}
{{- end }}