{{- if .Values.elastic.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- with .Values.elastic.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}  
  labels:
    app: elasticsearch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"    
  name: {{ .Release.Name }}-elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.elastic.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.elastic.ingress.url }}
      secretName: {{ .Values.elastic.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.elastic.ingress.url }}
    http:
      paths:
      - backend:
          service:
             name: {{ .Release.Name }}-elasticsearch-ingress
             port: 
               number: 9200
        path: /
        pathType: ImplementationSpecific
---
{{- end }}
