# Elastic APM
{{- if .Values.lsdmop.elastic.apm.enabled -}}
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.lsdmop.elastic.version }}
  count: {{ .Values.lsdmop.elastic.apm.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}
  kibanaRef:
    name: {{ .Release.Name }}
{{- end }}
