
# Kibana Ingress
{{- if or (eq .Values.lsdmop.clusterType "gke") (eq .Values.lsdmop.clusterType "rancher") -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    cert-manager.io/cluster-issuer: {{ .Values.lsdmop.elastic.kibana.ingress.annotations.certmanagerioclusterissuer }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'    
  labels:
    app: kibana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"    
  name: lsdmop-kb
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.lsdmop.kibanaURL }}
      secretName: {{ .Values.lsdmop.elastic.kibana.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.lsdmop.elastic.kibana.ingress.url }}
    http:
      paths:
      - backend:
          serviceName: lsdmop-kb-http
          servicePort: 5601
        path: /
        pathType: ImplementationSpecific
---
{{- end }}

# Kibana Route for Openshift
{{- if eq .Values.lsdmop.clusterType "openshift" -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Release.Name }}-kb-http
  name: {{ .Release.Name }}-kb-http
spec:
  host: {{ .Values.lsdmop.elastic.kibana.ingress.url }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }}-kb-http
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
    host: {{ .Values.lsdmop.elastic.kibana.ingress.url }}
    routerName: router
    wildcardPolicy: None
---
{{- end }}
