# Elastic ConfigMaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-filebeat-custom-files
  namespace: {{ .Release.Namespace }}
data:

  lsdmop-elastic-load-sample-dashboard.ndjson: |-
{{ .Files.Get "elastic/lsdmop-elastic-load-sample-dashboard.ndjson" | indent 4}}

  lsdmop-elastic-load-snapshot-repo.ndjson: |-
{{ .Files.Get "elastic/lsdmop-elastic-load-snapshot-repo.ndjson" | indent 4}}

  lsdmop-elastic-load-snapshot-policy-daily.ndjson: |-
{{ .Files.Get "elastic/lsdmop-elastic-load-snapshot-policy-daily.ndjson" | indent 4}}

  lsdmop-elastic-load-snapshot-policy-hourly.ndjson: |-
{{ .Files.Get "elastic/lsdmop-elastic-load-snapshot-policy-hourly.ndjson" | indent 4}}
---
