{{- if .Values.elastic.enterprise_search.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-entsearch
  namespace: lsdmop
{{- with .Values.elastic.enterprise_search.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.elastic.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.elastic.enterprise_search.ingress.url }}
      secretName: {{ .Values.elastic.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.elastic.enterprise_search.ingress.url }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: enterprise-search-{{ .Release.Name }}-ent-http
                port:
                  number: 3002
{{- end }}