{{- if .Values.lsdmop.elastic.license.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: eck-license
  namespace: {{ .Release.Namespace }}
  labels:
    license.k8s.elastic.co/scope: operator
type: Opaque
stringData:
  license: {{ .Values.lsdmop.elastic.license.key | toJson | quote }}
{{- end }}
