# Logstash ConfigMaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: {{ .Release.Namespace }}
data:
  logstash.conf: |-
{{ .Files.Get "logstash/pipeline-logstash.conf" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-lsdmop
  namespace: {{ .Release.Namespace }}
data:
  001-pipeline.conf: |-
{{ .Files.Get "logstash/pipeline-lsdmop.conf" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-patterns
  namespace: {{ .Release.Namespace }}
data:
  lsdmop-basic: |-
{{ .Files.Get "logstash/patterns-lsdmop-basic" | indent 4}}
  lsdmop-utility: |-
{{ .Files.Get "logstash/patterns-lsdmop-utility" | indent 4}}
---
