---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lsdmop
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: "32"
    limits.cpu: "128"
    requests.memory: "200Gi"
    limits.memory: "400Gi"
    requests.storage: "10Ti"
    persistentvolumeclaims: "20"
    requests.nvidia.com/gpu: 4
    configmaps: "150"
    pods: "150"
    replicationcontrollers: "50"
    secrets: "200"
    services: "200"
    services.loadbalancers: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lsdmop
  namespace: {{ .Release.Namespace }}
spec:
  limits:
    - max:
        cpu: "16"
        memory: 64Gi
      min:
        cpu: 10m
        memory: 4Mi
      type: Pod
    - default:
        cpu: 50m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      max:
        cpu: "6"
        memory: 32Gi
      maxLimitRequestRatio:
        cpu: "500"
      min:
        cpu: 10m
        memory: 4Mi
      type: Container
