# Elastic Metricbeat {{ .Release.Name }}-metricbeat
{{- if .Values.lsdmop.elastic.fleet.enabled -}}
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server-{{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  version: 8.2.2
  kibanaRef:
    name: {{ .Release.Name }}
  elasticsearchRefs:
  - name: {{ .Release.Name }}
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 2
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent-{{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  version: 8.2.2
  kibanaRef:
    name: {{ .Release.Name }}
  fleetServerRef:
    name: fleet-server-{{ .Release.Name }}
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        tolerations:
        - key: dedicated
          effect: "NoSchedule"
          operator: Exists

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
- kind: ServiceAccount
  name: elastic-agent
  namespace: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io

{{- end }}