# Elasticsearch
{{- if .Values.lsdmop.elastic.enabled -}}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  version: "{{ .Values.lsdmop.elastic.version }}"
  image: "{{ .Values.lsdmop.elastic.image }}"
  nodeSets:
    - config:
        node.store.allow_mmap: false
        #path.repo: /usr/share/elasticsearch/snapshots
        node.roles: ["master"]
      count: 1
      name: default
      podTemplate:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true'
              name: elasticsearch
              resources:
                limits:
                  cpu: '1000m'
                  memory: 2Gi
                requests:
                  cpu: '500m'
                  memory: 1Gi
      volumeClaimTemplates:
        - metadata:
            creationTimestamp: null
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: longhorn
          status: {}
    - config:
        node.store.allow_mmap: false
        #path.repo: /usr/share/elasticsearch/snapshots
        node.roles: ["data"]
        node.attr.data: hot
      count: 1
      name: hot-data
      podTemplate:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms5g -Xmx5g -Dlog4j2.formatMsgNoLookups=true'
              name: elasticsearch
              resources:
                limits:
                  cpu: '4000m'
                  memory: 8Gi
                requests:
                  cpu: '500m'
                  memory: 8Gi
      volumeClaimTemplates:
        - metadata:
            creationTimestamp: null
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: longhorn
          status: {}
    - config:
        node.store.allow_mmap: false
        #path.repo: /usr/share/elasticsearch/snapshots
        node.roles: ["data"]
        node.attr.data: warm
      count: 1
      name: warm-data
      podTemplate:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true'
              name: elasticsearch
              resources:
                limits:
                  cpu: '1000m'
                  memory: 2Gi
                requests:
                  cpu: '500m'
                  memory: 2Gi
      volumeClaimTemplates:
        - metadata:
            creationTimestamp: null
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
            storageClassName: longhorn
          status: {}          
{{- end }}
