
# Elasticsearch Ingress
{{- if or (eq .Values.lsdmop.clusterType "gke") (eq .Values.lsdmop.clusterType "rancher") -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    cert-manager.io/cluster-issuer: {{ .Values.lsdmop.elastic.ingress.annotations.certmanagerioclusterissuer }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'    
  labels:
    app: elasticsearch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"    
  name: lsdmop-elasticsearch
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.lsdmop.elasticURL }}
      secretName: {{ .Values.lsdmop.elastic.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.lsdmop.elastic.ingress.url }}
    http:
      paths:
      - backend:
          serviceName: lsdmop-es-http
          servicePort: 9200
        path: /
        pathType: ImplementationSpecific
---
{{- end }}