apiVersion: v2
name: lsdmop-operator
version: "2.14.0"
appVersion: "2.14.0"
# Disabling kubeVersion because GKE is dumb
# kubeVersion: ">=v1.11.0"
description: A Helm chart for LSDMOP
keywords:
  - lsdmop
  - kubernetes
  - prometheus
  - elastic
home: https://github.com/lsdopen/charts
sources:
  - https://github.com/lsdopen
maintainers:
  - name: LSD
    email: support@lsdopen.io
    url: https://lsdopen.io
deprecated: false

dependencies:
- name: eck-operator-crds
  version: "2.14.0"
  repository: https://helm.elastic.co
- name: eck-operator
  version: "2.14.0"
  repository: https://helm.elastic.co
