# Install with: helm install elasticagent ./elastic-agent --values=./values-elastic-agent-nonp.yaml --create-namespace=true -nlsdmopagent

agent:
  # -- elastic-agent version
  # @section -- 6 - Elastic-Agent Configuration
  version: 9.3.2
  # -- image configuration
  # @section -- 6 - Elastic-Agent Configuration
  image:
    repository: docker.elastic.co/elastic-agent/elastic-agent
    pullPolicy: IfNotPresent
    tag: "9.3.2"
  # -- image pull secrets
  # @section -- 6 - Elastic-Agent Configuration
  imagePullSecrets: []
  # -- generate kubernetes manifests or [ECK](https://github.com/elastic/cloud-on-k8s) CRDs
  # @section -- 6 - Elastic-Agent Configuration
  engine: k8s # k8s or eck
  # -- enable unprivileged mode
  # @section -- 6 - Elastic-Agent Configuration
  unprivileged: false
  fleet:
    pathPrefix: "/tmp" #required for Bottlerocket
    # -- enable elastic-agent managed
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    enabled: true
    # -- Fleet server URL
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    url: "https://<hostname>:443"
    # -- Fleet enrollment token
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    token: "<token>"
    # -- Communicate with Fleet with either insecure HTTP or unverified HTTPS
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    insecure: true
    # -- Enforce enrollment even if agent is already enrolled
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    force: true
    ca:
      # -- Value of the CA certificate for connecting to Fleet
      # @section -- 6.1 - Elastic-Agent Managed Configuration
      value: ""
      valueFromSecret:
        # -- Secret name for the CA certificate
        # @section -- 6.1 - Elastic-Agent Managed Configuration
        name: ""
        # -- Secret key for the CA certificate
        # @section -- 6.1 - Elastic-Agent Managed Configuration
        key: ""
    agentCert:
      # -- Value of Elastic Agent client certificate for Fleet Server mTLS
      # @section -- 6.1 - Elastic-Agent Managed Configuration
      value: ""
      valueFromSecret:
        # -- Secret name for the Elastic Agent client certificate
        # @section -- 6.1 - Elastic-Agent Managed Configuration
        name: ""
        # -- Key in the secret for the Elastic Agent client certificate
        # @section -- 6.1 - Elastic-Agent Managed Configuration
        key: ""
    agentCertKey:
      # -- Value of Elastic Agent client private key for Fleet Server mTLS
      # @section -- 6.1 - Elastic-Agent Managed Configuration
      value: ""
      valueFromSecret:
        # -- Secret name for the Elastic Agent client private key
        # @section -- 6.1 - Elastic-Agent Managed Configuration
        name: ""
        # -- Key in the secret for the Elastic Agent client private key
        # @section -- 6.1 - Elastic-Agent Managed Configuration
        key: ""
    # -- Token name to use for fetching token from Kibana if the enrollment token is not supplied
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    tokenName: ""
    # -- Token policy name to use for fetching token from Kibana if the enrollment token is not supplied
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    policyName: ""
    # -- Kibana host to fallback if enrollment token is not supplied
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    kibanaHost: ""
    # -- Kibana username to fallback if enrollment token is not supplied
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    kibanaUser: ""
    # -- Kibana password to fallback if enrollment token is not supplied
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    kibanaPassword: ""
    kibanaCA:
      # -- Value of the CA certificate for Kibana if the enrollment token is not supplied
      # @section -- 6.1 - Elastic-Agent Managed Configuration
      value: ""
      valueFromSecret:
        # -- Secret name for the Kibana CA certificate
        # @section -- 6.1 - Elastic-Agent Managed Configuration
        name: ""
        # -- Key in the secret for the Kibana CA certificate
        # @section -- 6.1 - Elastic-Agent Managed Configuration
        key: ""
    # -- Service token to use when connecting to Kibana if the enrollment token is not supplied
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    kibanaServiceToken: ""
    # -- Agent preset to deploy
    # @section -- 6.1 - Elastic-Agent Managed Configuration
    preset: perNode
  # -- Map of deployment presets for the Elastic Agent. The key of the map is the name of the preset. See more for the presets
  # required by the built-in Kubernetes integration [here](./values.yaml)
  # @notationType -- map[string]{}
  # @section -- 6 - Elastic-Agent Configuration
  # @default -- `{ "perNode" : {...}, "clusterWide": {...}}`
  presets:
    #  examplePreset:
    #    mode: [deployment, statefulset, daemonset]
    #    replicaCount: 1
    #    labels: {}
    #    hostPID: boolean
    #    hostNetwork: boolean
    #    imagePullPolicy: [Always, IfNotPresent, Never]
    #    annotations: {}
    #    affinity: {}
    #    initContainers: []
    #    extraContainers: []
    #    resources: {}
    #    securityContext: {}
    #    nodeSelector: {}
    #    tolerations: []
    #    topologySpreadConstraints: []
    #    extraEnv: []
    #    statePersistence: [HostPath, EmptyDir, None]
    #    extraVolumes: []
    #    extraVolumeMounts: []
    #    https://github.com/elastic/elastic-agent/blob/main/_meta/elastic-agent.yml
    #    agent.monitoring: {}
    #    https://www.elastic.co/guide/en/fleet/current/providers.html
    #    providers: {}
    #
    # clusterWide preset is required by the built-in kubernetes integration
    clusterWide:
      mode: deployment
      serviceAccount:
        create: true
      clusterRole:
        create: true
      resources:
        limits:
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 400Mi
      nodeSelector:
        kubernetes.io/os: linux
      statePersistence: EmptyDir
      extraVolumes: []
      extraEnvs:
        - name: ELASTIC_NETINFO
          value: "false"
      agent:
        monitoring:
          namespace: lsdmopagent
          use_output: default
          enabled: true
          logs: true
          metrics: true
      providers:
        kubernetes_leaderelection:
          enabled: true
        kubernetes:
          node: ${NODE_NAME}
          scope: cluster
    perNode:
      ## required by the built-in kubernetes integration
      mode: daemonset
      # securityContext:
      #   privileged: true
      #   runAsUser: 0
      #   fsGroup: 0
      serviceAccount:
        create: true
      clusterRole:
        create: true
      hostNetwork: true
      resources:
        limits:
          memory: 1000Mi
        requests:
          cpu: 100m
          memory: 400Mi
      nodeSelector:
        kubernetes.io/os: linux
        #node-role: web
      tolerations:
        - key: node-role
          operator: Equal
          value: web
          effect: NoSchedule
        - key: node-role
          operator: Equal
          value: x-finch
          effect: NoSchedule
      statePersistence: HostPath
      extraEnvs:
        - name: ELASTIC_NETINFO
          value: "false"
      agent:
        monitoring:
          namespace: lsdmopagent
          use_output: default
          enabled: true
          logs: true
          metrics: true
      providers:
        kubernetes:
          node: ${NODE_NAME}
          scope: node
    autoOps:
      mode: deployment
      serviceAccount:
        create: true
      clusterRole:
        create: true
      nodeSelector:
        kubernetes.io/os: linux
kube-state-metrics:
  enabled: false
  fullnameOverride: "kube-state-metrics"
  replicas: 1
