apiVersion: v2
name: lsdmop
version: "6.0.5"
appVersion: "1.0.2"
# Disabling kubeVersion because GKE is dumb
# kubeVersion: ">=v1.11.0"
description: A Helm chart for LSDMOP
keywords:
  - lsdmop
  - kubernetes
  - prometheus
  - elastic
home: https://github.com/lsdopen/charts
sources:
  - https://github.com/lsdopen
maintainers:
  - name: LSD
    email: support@lsdopen.io
    url: https://lsdopen.io
deprecated: false
