apiVersion: v2
name: lsdmop
version: "4.7.10"
appVersion: "1.0.2"
# Disabling kubeVersion because GKE is dumb
# kubeVersion: ">=v1.11.0"
description: A Helm chart for LSDMOP
keywords:
  - lsdmop
  - kubernetes
  - prometheus
  - elastic
home: https://github.com/lsdopen/charts
sources:
  - https://github.com/lsdopen
maintainers:
  - name: LSD
    email: support@lsdopen.io
    url: https://lsdopen.io
deprecated: false

dependencies:
- name: kube-state-metrics
  version: "5.7.0"
  repository: https://prometheus-community.github.io/helm-charts
- name: eck-operator
  version: "2.11.1"
  repository: https://helm.elastic.co
- name: logstash
  version: "7.17.3"
  repository: https://helm.elastic.co
